<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9; border-right: 5px solid #20639b; padding: 8px 18px;">
  <h1 style="color:#173f5f; margin-bottom:4px;">نوت‌بوک 11: مبانی NumPy</h1>
  <p><b>سطح:</b> مقدماتی تا متوسط &nbsp; | &nbsp; <b>روش مطالعه:</b> توضیح کوتاه ← اجرای مثال ← تغییر مثال ← حل تمرین</p>
  <h3>هدف‌های یادگیری</h3>
  <ul><li>ساخت آرایه و شناخت shape و dtype</li>
<li>اندیس‌گذاری و برش چندبعدی</li>
<li>محاسبهٔ برداری به‌جای حلقه</li>
<li>فیلتر و خلاصه‌سازی دادهٔ عددی</li></ul>
  <p style="background:#eef6fb; padding:10px; border-radius:8px;">همهٔ سلول‌ها را به‌ترتیب اجرا کنید. برای یادگیری بهتر، مقدار ورودی‌ها را تغییر دهید و نتیجه را پیش‌بینی کنید.</p>
</div>

<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9;">
  <h2 style="color:#173f5f;">چرا NumPy؟</h2>
  <p>NumPy آرایهٔ چندبعدی سریع و ابزارهای محاسبات عددی ارائه می‌کند. برخلاف لیست پایتون، اعضای آرایه معمولاً یک نوع داده دارند.</p>
</div>

In [2]:
# Import NumPy with its standard alias
import numpy as np

values = np.array([12, 15, 18, 21], dtype=np.float64)
print(values)
print("Shape:", values.shape)
print("Dimensions:", values.ndim)
print("Data type:", values.dtype)


[12. 15. 18. 21.]
Shape: (4,)
Dimensions: 1
Data type: float64


<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9;">
  <h2 style="color:#173f5f;">ساخت آرایه</h2>
  <p><code>zeros</code>، <code>ones</code>، <code>arange</code> و <code>linspace</code> آرایه‌های رایج را بدون نوشتن تک‌تک اعضا می‌سازند.</p>
</div>

In [3]:
# Create arrays with common constructors
print(np.zeros((2, 3)))
print(np.ones(4, dtype=int))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))


[[0. 0. 0.]
 [0. 0. 0.]]
[1 1 1 1]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9;">
  <h2 style="color:#173f5f;">اندیس و برش</h2>
  <p>در آرایهٔ دوبعدی، بعد اول ردیف و بعد دوم ستون است. برش‌ها معمولاً view می‌سازند؛ بنابراین تغییر آن‌ها می‌تواند آرایهٔ اصلی را تغییر دهد.</p>
</div>

In [4]:
# Select rows, columns, and sub-arrays
matrix = np.array([
    [10, 12, 14],
    [16, 18, 20],
    [22, 24, 26],
])

print("Single item:", matrix[1, 2])
print("First row:", matrix[0])
print("Second column:", matrix[:, 1])
print("Top-left block:\n", matrix[:2, :2])


Single item: 20
First row: [10 12 14]
Second column: [12 18 24]
Top-left block:
 [[10 12]
 [16 18]]


<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9;">
  <h2 style="color:#173f5f;">محاسبهٔ برداری و Broadcasting</h2>
  <p>عملگر روی کل آرایه اجرا می‌شود. Broadcasting اجازه می‌دهد آرایه‌های سازگار با شکل متفاوت، بدون تکرار دستی با هم محاسبه شوند.</p>
</div>

In [5]:
# Apply vectorized operations
prices = np.array([120_000, 85_000, 240_000, 60_000])
discounted = prices * 0.9

monthly_sales = np.array([
    [120, 140, 135],
    [90, 110, 105],
])
growth_factors = np.array([1.0, 1.05, 1.10])
projected = monthly_sales * growth_factors

print(discounted)
print(projected)


[108000.  76500. 216000.  54000.]
[[120.  147.  148.5]
 [ 90.  115.5 115.5]]


<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9;">
  <h2 style="color:#173f5f;">فیلتر و آمار</h2>
  <p>شرط روی آرایه یک ماسک Boolean می‌سازد. توابع تجمیعی مانند میانگین، مجموع، کمینه و بیشینه کل داده را خلاصه می‌کنند.</p>
</div>

In [6]:
# Filter and summarize numeric data
scores = np.array([12, 17.5, 8, 19, 15, 6.5])
passed = scores[scores >= 10]

print("Passed:", passed)
print("Count:", passed.size)
print("Average:", passed.mean())
print("Highest:", scores.max())


Passed: [12.  17.5 19.  15. ]
Count: 4
Average: 15.875
Highest: 19.0


<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9;">
  <h2 style="color:#173f5f;">تمرین کوتاه</h2>
  <div style="background:#fff7df; border:1px solid #f0c36d; padding:12px; border-radius:8px;">آرایه‌ای از دماهای هفت روز بسازید. دماهای بالاتر از میانگین، دامنهٔ تغییرات و دمای تبدیل‌شده به فارنهایت را محاسبه کنید.</div>
</div>

<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9;">
  <h2 style="color:#173f5f;">پاسخ پیشنهادی</h2>
  <p>ابتدا پاسخ خودتان را بنویسید؛ سپس این سلول را اجرا و مقایسه کنید.</p>
</div>

In [7]:
# Analyze weekly temperatures
temperatures_c = np.array([18.5, 21, 23.5, 19, 25, 24, 20])
average_c = temperatures_c.mean()
above_average = temperatures_c[temperatures_c > average_c]
temperature_range = np.ptp(temperatures_c)
temperatures_f = temperatures_c * 9 / 5 + 32

print("Average C:", round(average_c, 2))
print("Above average:", above_average)
print("Range:", temperature_range)
print("Fahrenheit:", temperatures_f)


Average C: 21.57
Above average: [23.5 25.  24. ]
Range: 6.5
Fahrenheit: [65.3 69.8 74.3 66.2 77.  75.2 68. ]


<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9;">
  <h2 style="color:#173f5f;">جمع‌بندی</h2>
  <p>قدرت اصلی NumPy در عملیات برداری است؛ پیش از نوشتن حلقه برای دادهٔ عددی، بررسی کنید آیا عملیات مستقیم روی آرایه ممکن است.</p>
</div>