<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9; border-right: 5px solid #20639b; padding: 8px 18px;">
  <h1 style="color:#173f5f; margin-bottom:4px;">نوت‌بوک 12: NumPy کاربردی: شکل، محور، دادهٔ گمشده و تصادفی</h1>
  <p><b>سطح:</b> متوسط &nbsp; | &nbsp; <b>روش مطالعه:</b> توضیح کوتاه ← اجرای مثال ← تغییر مثال ← حل تمرین</p>
  <h3>هدف‌های یادگیری</h3>
  <ul><li>تغییر شکل و ترکیب آرایه‌ها</li>
<li>محاسبه روی محورهای مختلف</li>
<li>مدیریت NaN</li>
<li>تولید دادهٔ تکرارپذیر با random generator</li></ul>
  <p style="background:#eef6fb; padding:10px; border-radius:8px;">همهٔ سلول‌ها را به‌ترتیب اجرا کنید. برای یادگیری بهتر، مقدار ورودی‌ها را تغییر دهید و نتیجه را پیش‌بینی کنید.</p>
</div>

<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9;">
  <h2 style="color:#173f5f;">reshape و transpose</h2>
  <p><code>reshape</code> چیدمان را بدون تغییر تعداد اعضا عوض می‌کند. ترانهاده، ردیف و ستون را جابه‌جا می‌کند.</p>
</div>

In [1]:
# Reshape a flat sequence into a table
import numpy as np

values = np.arange(1, 13)
table = values.reshape(3, 4)

print(table)
print("Transposed:\n", table.T)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transposed:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9;">
  <h2 style="color:#173f5f;">محور یا axis</h2>
  <p>در آرایهٔ دوبعدی، <code>axis=0</code> ردیف‌ها را جمع و برای هر ستون خروجی می‌سازد؛ <code>axis=1</code> ستون‌ها را جمع و برای هر ردیف خروجی می‌سازد.</p>
</div>

In [ ]:
# Aggregate rows and columns
sales = np.array([
    [120, 135, 150, 145],
    [90, 105, 110, 125],
    [180, 175, 190, 210],
])

print("Totals by month:", sales.sum(axis=0))
print("Totals by product:", sales.sum(axis=1))
print("Best product index:", sales.sum(axis=1).argmax())


<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9;">
  <h2 style="color:#173f5f;">ترکیب آرایه‌ها</h2>
  <p><code>concatenate</code> روی محور موجود ترکیب می‌کند؛ <code>vstack</code> ردیف و <code>hstack</code> ستون اضافه می‌کند.</p>
</div>

In [ ]:
# Combine compatible arrays
first_quarter = np.array([[10, 12, 14], [8, 11, 13]])
second_quarter = np.array([[15, 16, 18], [14, 15, 17]])

six_months = np.hstack([first_quarter, second_quarter])
new_product = np.array([[9, 10, 12, 13, 14, 16]])
all_products = np.vstack([six_months, new_product])

print(all_products)


<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9;">
  <h2 style="color:#173f5f;">NaN و دادهٔ گمشده</h2>
  <p><code>NaN</code> نمایندهٔ عدد گمشده است. نسخه‌های <code>nanmean</code> و <code>nansum</code> هنگام محاسبه آن را نادیده می‌گیرند.</p>
</div>

In [ ]:
# Fill missing values with the column mean
readings = np.array([
    [12.0, np.nan, 18.0],
    [14.0, 16.0, np.nan],
    [13.0, 15.0, 19.0],
])

column_means = np.nanmean(readings, axis=0)
missing_rows, missing_cols = np.where(np.isnan(readings))
filled = readings.copy()
filled[missing_rows, missing_cols] = column_means[missing_cols]

print("Column means:", column_means)
print("Filled data:\n", filled)


<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9;">
  <h2 style="color:#173f5f;">اعداد تصادفی تکرارپذیر</h2>
  <p>با <code>default_rng</code> و seed ثابت، نمونهٔ تصادفی در هر اجرا یکسان می‌شود؛ این موضوع برای آموزش و آزمایش مهم است.</p>
</div>

In [ ]:
# Generate reproducible sample data
rng = np.random.default_rng(seed=42)
sample = rng.normal(loc=100, scale=15, size=8)

print(np.round(sample, 2))
print("Sample mean:", round(sample.mean(), 2))


<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9;">
  <h2 style="color:#173f5f;">تمرین کوتاه</h2>
  <div style="background:#fff7df; border:1px solid #f0c36d; padding:12px; border-radius:8px;">نمره‌های سه دانشجو در چهار درس را در یک آرایه قرار دهید؛ میانگین هر دانشجو، میانگین هر درس و نمرهٔ استانداردشدهٔ کل آرایه را محاسبه کنید.</div>
</div>

<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9;">
  <h2 style="color:#173f5f;">پاسخ پیشنهادی</h2>
  <p>ابتدا پاسخ خودتان را بنویسید؛ سپس این سلول را اجرا و مقایسه کنید.</p>
</div>

In [ ]:
# Summarize and standardize a score matrix
scores = np.array([
    [16, 18, 15, 19],
    [12, 14, 17, 15],
    [19, 18, 20, 17],
], dtype=float)

student_means = scores.mean(axis=1)
course_means = scores.mean(axis=0)
standardized = (scores - scores.mean()) / scores.std()

print("Student means:", student_means)
print("Course means:", course_means)
print("Standardized:\n", np.round(standardized, 2))


<div dir="rtl" style="text-align: right; font-family: Tahoma, Arial, sans-serif; line-height: 1.9;">
  <h2 style="color:#173f5f;">نکتهٔ نهایی</h2>
  <p>هنگام محاسبهٔ چندبعدی همیشه شکل آرایه و معنای هر محور را پیش از نوشتن فرمول مشخص کنید.</p>
</div>