<div dir="rtl" style="text-align:right; font-family:Tahoma,Arial,sans-serif; line-height:1.9; border-right:5px solid #20639b; padding:8px 18px;">
  <h1 style="color:#173f5f; margin-bottom:4px;">نوت‌بوک 13: جبر خطی کاربردی با NumPy</h1>
  <p><b>سطح:</b> متوسط &nbsp; | &nbsp; <b>نوع درس:</b> تکمیلی و کاربردی</p>
  <h3>هدف‌های یادگیری</h3>
  <ul><li>نمایش بردار و ماتریس با ndarray</li>
<li>محاسبهٔ ضرب داخلی و ضرب ماتریسی</li>
<li>حل دستگاه معادلات خطی</li>
<li>شناخت رتبه، دترمینان و عدد وضعیت</li>
<li>محاسبهٔ مقدار ویژه و برازش کمترین مربعات</li></ul>
</div>

<div dir="rtl" style="text-align:right; font-family:Tahoma,Arial,sans-serif; line-height:1.9;">
  <h2 style="color:#173f5f;">بردار و ماتریس</h2>
  <p>بردار آرایه‌ای یک‌بعدی و ماتریس آرایه‌ای دوبعدی است. شکل آرایه تعیین می‌کند عملیات چگونه انجام شود. در جبر خطی، نوع <code>float</code> معمولاً انتخاب امن‌تری برای محاسبات است.</p>
</div>

In [1]:
# Create vectors and a matrix
import numpy as np

vector_a = np.array([2.0, 1.0, 3.0])
vector_b = np.array([1.0, 4.0, -2.0])
matrix_a = np.array([
    [2.0, 1.0, 0.0],
    [1.0, 3.0, 1.0],
    [0.0, 2.0, 4.0],
])

print("Vector shape:", vector_a.shape)
print("Matrix shape:", matrix_a.shape)
print("Transpose:\n", matrix_a.T)


Vector shape: (3,)
Matrix shape: (3, 3)
Transpose:
 [[2. 1. 0.]
 [1. 3. 2.]
 [0. 1. 4.]]


<div dir="rtl" style="text-align:right; font-family:Tahoma,Arial,sans-serif; line-height:1.9;">
  <h2 style="color:#173f5f;">ضرب عضو به عضو، داخلی و ماتریسی</h2>
  <p><code>*</code> ضرب عضو به عضو است. <code>np.dot</code> یا عملگر <code>@</code> ضرب داخلی و ماتریسی را انجام می‌دهد. این تفاوت یکی از مهم‌ترین نکات NumPy است.</p>
</div>

In [2]:
# Compare element-wise and linear-algebra products
elementwise = vector_a * vector_b
dot_product = vector_a @ vector_b
matrix_vector = matrix_a @ vector_a
matrix_product = matrix_a @ matrix_a.T

print("Element-wise:", elementwise)
print("Dot product:", dot_product)
print("Matrix-vector:", matrix_vector)
print("Matrix product:\n", matrix_product)


Element-wise: [ 2.  4. -6.]
Dot product: 0.0
Matrix-vector: [ 5.  8. 14.]
Matrix product:
 [[ 5.  5.  2.]
 [ 5. 11. 10.]
 [ 2. 10. 20.]]


<div dir="rtl" style="text-align:right; font-family:Tahoma,Arial,sans-serif; line-height:1.9;">
  <h2 style="color:#173f5f;">طول، فاصله و زاویه</h2>
  <p>نورم اقلیدسی طول بردار را می‌دهد. فاصلهٔ دو نقطه نورم تفاضل آن‌هاست. شباهت کسینوسی نیز زاویهٔ میان دو بردار را به عددی بین منفی یک و یک تبدیل می‌کند.</p>
</div>

In [3]:
# Measure vector magnitude, distance, and cosine similarity
length_a = np.linalg.norm(vector_a)
distance = np.linalg.norm(vector_a - vector_b)
cosine_similarity = (
    vector_a @ vector_b
    / (np.linalg.norm(vector_a) * np.linalg.norm(vector_b))
)

print("Length:", round(length_a, 3))
print("Distance:", round(distance, 3))
print("Cosine similarity:", round(cosine_similarity, 3))


Length: 3.742
Distance: 5.916
Cosine similarity: 0.0


<div dir="rtl" style="text-align:right; font-family:Tahoma,Arial,sans-serif; line-height:1.9;">
  <h2 style="color:#173f5f;">حل دستگاه معادلات</h2>
  <p>دستگاه <code>Ax=b</code> را با <code>np.linalg.solve</code> حل کنید. محاسبهٔ مستقیم معکوس هم کندتر است و هم از نظر عددی معمولاً انتخاب ضعیف‌تری است.</p>
</div>

In [5]:
# Solve a linear system and verify the result
coefficients = np.array([
    [2.0, 1.0, -1.0],
    [-3.0, -1.0, 2.0],
    [-2.0, 1.0, 2.0],
])
constants = np.array([8.0, -11.0, -3.0])

solution_vector = np.linalg.solve(coefficients, constants)
verification = coefficients @ solution_vector

print("Solution:", solution_vector)
print("Verified:", np.allclose(verification, constants))


Solution: [ 2.  3. -1.]
Verified: True


<div dir="rtl" style="text-align:right; font-family:Tahoma,Arial,sans-serif; line-height:1.9;">
  <h2 style="color:#173f5f;">رتبه، دترمینان و پایداری</h2>
  <p>رتبه تعداد ابعاد مستقل ماتریس را نشان می‌دهد. دترمینان نزدیک صفر می‌تواند نشانهٔ تکین یا نزدیک‌تکین بودن باشد. عدد وضعیت بزرگ یعنی جواب نسبت به خطای کوچک ورودی حساس است.</p>
</div>

In [6]:
# Inspect matrix properties
determinant = np.linalg.det(matrix_a)
rank = np.linalg.matrix_rank(matrix_a)
condition_number = np.linalg.cond(matrix_a)

print("Determinant:", round(determinant, 3))
print("Rank:", rank)
print("Condition number:", round(condition_number, 3))


Determinant: 16.0
Rank: 3
Condition number: 4.645


<div dir="rtl" style="text-align:right; font-family:Tahoma,Arial,sans-serif; line-height:1.9;">
  <h2 style="color:#173f5f;">مقدار و بردار ویژه</h2>
  <p>در رابطهٔ <code>Av=λv</code>، جهت بردار ویژه پس از تبدیل عوض نمی‌شود و فقط مقیاس آن تغییر می‌کند. این مفهوم در PCA، سیستم‌های پویا و تحلیل شبکه کاربرد دارد.</p>
</div>

In [7]:
# Compute eigenvalues and eigenvectors of a symmetric matrix
covariance_like = np.array([
    [4.0, 2.0],
    [2.0, 3.0],
])

eigenvalues, eigenvectors = np.linalg.eigh(covariance_like)
order = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[order]
eigenvectors = eigenvectors[:, order]

print("Eigenvalues:", np.round(eigenvalues, 3))
print("Eigenvectors:\n", np.round(eigenvectors, 3))


Eigenvalues: [5.562 1.438]
Eigenvectors:
 [[-0.788  0.615]
 [-0.615 -0.788]]


<div dir="rtl" style="text-align:right; font-family:Tahoma,Arial,sans-serif; line-height:1.9;">
  <h2 style="color:#173f5f;">کمترین مربعات</h2>
  <p>وقتی تعداد معادلات بیشتر از مجهول‌هاست و جواب دقیق وجود ندارد، <code>lstsq</code> ضرایبی را پیدا می‌کند که مجموع مربع خطاها را کمینه کند.</p>
</div>

In [8]:
# Fit a straight line with least squares
x_values = np.array([1, 2, 3, 4, 5], dtype=float)
y_values = np.array([2.2, 3.9, 6.1, 8.2, 9.8])
design_matrix = np.column_stack([x_values, np.ones_like(x_values)])

slope, intercept = np.linalg.lstsq(
    design_matrix,
    y_values,
    rcond=None,
)[0]
predictions = slope * x_values + intercept
rmse = np.sqrt(np.mean((y_values - predictions) ** 2))

print("Slope:", round(slope, 3))
print("Intercept:", round(intercept, 3))
print("RMSE:", round(rmse, 3))


Slope: 1.95
Intercept: 0.19
RMSE: 0.146


<div dir="rtl" style="text-align:right; font-family:Tahoma,Arial,sans-serif; line-height:1.9;">
  <h2 style="color:#173f5f;">تمرین</h2>
  <div style="background:#fff7df; border:1px solid #f0c36d; padding:12px; border-radius:8px;">سه محصول از دو مادهٔ اولیه مصرف می‌کنند. ماتریس مصرف <code>[[2,1,3],[1,2,1]]</code> و تعداد تولید <code>[100,80,120]</code> است. مصرف کل هر ماده را با ضرب ماتریسی محاسبه کنید.</div>
</div>

<div dir="rtl" style="text-align:right; font-family:Tahoma,Arial,sans-serif; line-height:1.9;">
  <h2 style="color:#173f5f;">پاسخ پیشنهادی</h2>
  <p>ابتدا پاسخ خودتان را بنویسید و سپس با پاسخ پیشنهادی مقایسه کنید.</p>
</div>

In [9]:
# Calculate total material requirements
material_per_product = np.array([
    [2, 1, 3],
    [1, 2, 1],
])
production_plan = np.array([100, 80, 120])

total_materials = material_per_product @ production_plan
print("Total material requirements:", total_materials)


Total material requirements: [640 380]


<div dir="rtl" style="text-align:right; font-family:Tahoma,Arial,sans-serif; line-height:1.9;">
  <h2 style="color:#173f5f;">جمع‌بندی</h2>
  <p>در مسائل واقعی ابتدا شکل‌ها را بررسی کنید، برای دستگاه از solve و برای برازش از lstsq استفاده کنید و پیش از اعتماد به جواب، عدد وضعیت را در نظر بگیرید.</p>
</div>